### ISSUE TITLE
[DESIGN] 대회 상세 페이지 수정

### ISSUE THREAD

**Issue by llddang** [pnu-code-place/code-place#202]
## **TODO(필수)**
- [x]  컨테스트 제출물 빼기
- [ ]  대회 메인화면 이쁘게 바꾸기
- [x]  대회의 ‘대회’를 ‘대회개요’로 바꾸고 대회 메인화면에 공지사항 넣을 칸 넣기
