### ISSUE TITLE
[FEAT] 관리자 페이지에 대회 관리 제출물 관리 페이지 구현

### ISSUE THREAD

**Issue by llddang** [pnu-code-place/code-place#211]
## **TODO(필수)**
-관리자 페이지에 대회 관리 제출물 관리 페이지 추가할 예정입니다.

- [x] 클라이언트 대회 랭킹 페이지의 순위 엑셀표 다운로드 기능 삭제
- 대회 현황페이지
  - [ ] 참가인원 현황 구현 및 api 연결
  - [ ] 제출 현황 구현 및 api 연결
  - [ ] 성적 결과물 엑셀표 다운 버튼 구현 및 api 연결
