### ISSUE TITLE
[FE] 대회의 랭킹 페이지 디자인 수정 및 기능 추가

### ISSUE THREAD

**Issue by llddang** [pnu-code-place/code-place#234]
## **TODO(필수)**
- [x] 대회의 type이 ACM인 경우 총점 항목 삭제
       + 도움말로 pass or no pass라서 총점 표시가 안 된다고 설명 추가
- [x] 랭킹의 제목이 길면 4~5줄로 길게 표시됨
       => 최대 100 ~ 150px 로 설정 후, 말줄임 사용 + table에 가로 스크롤
- [x]  ~랭킹에 어드민도 표시하다록 api 수정 중
        위 api 반영 후 어드민 추가를 체크박스를 이용하여 조절~
- [x] 랭킹 테이블에 user 프로필 추가
