### ISSUE TITLE
[FE] 대회 상세 페이지 UI 변경

### ISSUE THREAD

**Issue by llddang** [pnu-code-place/code-place#237]
## **TODO(필수)**
- [x] 문제 목록 페이지에 ACM 대회 타입 관련 도움말 추가
- [x] 문제 목록 페이지에서 ACM 대회일 때, 총점 삭제
- [x] 랭킹 페이지의 header 변경 (# -> 순위, 일반 사용자 목록 -> 대회 참가자)
- [x] 랭킹 페이지의 api 받아와지지 않는 이슈 확인
- [x] 개요 페이지의 종료 시간구하는 로직 확인
